default_context:
  name: "fluxviz"
  version: "0.1.0"
  slug: "fluxviz"
  command: "fluxviz"
  cli: "argparse"
  config: "y"
  compat: "custom"
  jupyter: "y"
  sqlite: "y"
  pypy: "y"
  travis: "n"
  appveyor: "n"
  description: "An SBML Visualizer"
  author: "Achilles Rasquinha"
  email: "achillesrasquinha@gmail.com"
  keywords: "sbml visualizer converter"
  license: "MIT License"
  repo_service: "https://github.com"
  repo_service_username: "achillesrasquinha"
  repo_service_reponame: "fluxviz"
  docker_service_username: "achillesrasquinha"
  docker_service_reponame: "fluxviz"
  github_action: "n"
  ml: "n"
  editor: "vscode"
  url: "https://github.com/achillesrasquinha/fluxviz"