name: Jobs

on:
  push:
    branches:
      - master
  # schedule:
  #   - cron: "*/30 * * * *"

env:
  COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ENVIRONMENT: test
  VERBOSE: true
  TERM: xterm

  PIPUPGRADE_JOBS_GITHUB_USERNAME: achillesrasquinha
  PIPUPGRADE_JOBS_GITHUB_OAUTH_TOKEN: ${{ secrets.PIPUPGRADE_JOBS_GITHUB_OAUTH_TOKEN }}

jobs:
  jobs:
    name: Test
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest

    # strategy:
    #   fail-fast: false
    #   matrix:
    #     os: [ubuntu-latest]
    #     python-version: [3.9]
    
    steps:
      - uses: actions/checkout@v2
      - name: Show ref
        run: |
          echo "Checking out $GITHUB_REF..."
      - uses: actions/setup-python@v2
        name: Set up Python 3.9
        with:
          python-version: 3.9
      - name: Upgrade PIP and packages
        run: |
          python -m pip install --upgrade pip setuptools wheel
      - name: Install dependencies
        run: |
          pip install -r requirements-jobs.txt
          python setup.py develop
      # - name: Run Jobs
      #   run: |
      #     python -c "import pipupgrade as pu; pu.run_all_jobs()"